# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dc8fc5c17a359d4f1953604b090f852e03166386aa2f3529d34f1ff2626141fca1b98aa4ce2850ab823e4e3775c3e3182102158ec2134d4be8905d02bc1930f

test:
  secret_key_base: 9f165a5ff725999f9035403b3239ea3f9e9575e65bdc36b533e258987eb21bfcd1753d318454f148997e76ffa3f840835028e75d3261a6f5f19df9d9df3d5de5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
